# Extra source files needed for simulation but not generated by uvm-tb --
# e.g. sub-modules instantiated by 'axi_stream' itself, or any other file
# your DUT needs compiled alongside it. One path per line, relative to this
# directory (or absolute); '#' starts a comment.
#
# Unlike filelist.f, uvm-tb creates this file once and never overwrites or
# regenerates it -- edit it freely, including after a --force regenerate.
